const images = {
  app_mockup: require("./img_main.svg"),
  avatar_parents: require("./img_avatar_parent.svg"),
  avatar_teacher: require("./img_avatar_teacher.svg"),
  btn_app_store: require("./btn_app_store.svg"),
  btn_google_play: require("./btn_google_play.svg"),
  function_1: require("./img_msg_reserv_popup.svg"),
  function_2: require("./img_plugoff_noti.svg"),
  function_3: require("./img_chat_list.svg"),
  guide_AddOtherClass_1: require("./img_AddOtherClass_1.png"),
  guide_AddOtherClass_2: require("./img_AddOtherClass_2.png"),
  guide_addClass_1: require("./img_addClass_1.png"),
  guide_addClass_2: require("./img_addClass_2.png"),
  guide_EditChildName_1: require("./img_EditChildName_1.png"),
  guide_EditChildName_2: require("./img_EditChildName_2.png"),
  guide_editClass_1: require("./img_EditClass_1.png"),
  guide_editClass_2: require("./img_EditClass_2.png"),
  guide_editClass_3: require("./img_EditClass_3.png"),
  guide_inviteToClass_1: require("./img_inviteToClass_1.png"),
  guide_inviteToClass_2: require("./img_inviteToClass_2.png"),
  guide_officeHourSetting_1: require("./img_OfficeHourSetting_1.png"),
  guide_officeHourSetting_2: require("./img_OfficeHourSetting_2.png"),
  guide_ParentAddClass_1: require("./img_ParentAddClass_1.png"),
  guide_ParentAddClass_2: require("./img_ParentAddClass_2.png"),
  guide_ParentRegister_1: require("./img_ParentRegister_1.png"),
  guide_ParentRegister_2: require("./img_ParentRegister_2.png"),
  guide_ParentRegister_3: require("./img_ParentRegister_3.png"),
  guide_register_1: require("./img_resgister_1.png"),
  guide_register_2: require("./img_resgister_2.png"),

  ic_appicon_primary: require("./ic_appicon_primary.svg"),
  logo: require("./logo.svg")
};

export default images;
